### ISSUE TITLE
Impossible to clone repository

### ISSUE THREAD

**Issue by ssosas** [linto-ai/linto-wakemeup#1]
Hi all,
It is not possible to clone the repo, only authorized people can, just see a chunk of my console logs next.
Could you please open this repo to anonymous users?

Thanks a lot!

Sergio

===================== LOGS ==============
Clonage dans 'wake-me-up'...
The authenticity of host '[ci.linagora.com]:7999 ([54.36.8.54]:7999)' can't be established.
RSA key fingerprint is SHA256:cTjNgeiEbRqF/PvXJlthz2EDymP1b3+Wzs3QgIAhHQ8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[ci.linagora.com]:7999,[54.36.8.54]:7999' (RSA) to the list of known hosts.
********************************************************************
*                THIS IS A PRIVATE COMPUTER SYSTEM.                *
*                                                                  *
*       This system is for the use of authorized users only !      *
*    Disconnect IMMEDIATELY if you are not an authorized user !    *
.....
git@ci.linagora.com: Permission denied (publickey).
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.

**Comment by ssosas** [comment]
Well in fact just need to modify the doc to use https instead of ssh on the git clone command ;)

**Comment by damienlaine** [comment]
Yeah, that's the point :) This repo was hosted on our gitlab previously. Sry.
