### ISSUE TITLE
microphone not captured

### ISSUE THREAD

**Issue by PhMakowski** [linto-ai/linto-wakemeup#3]
Hi,
with the latest master, all seems to be ok, the web site is running, but th microphone is not captured, so no recording.
tested with Firefox under GNU/Linux, and under an Android Phone.

**Comment by rlopezdev** [comment]
Hi @PhMakowski,
The web audio API works only with HTTPS now.
For chrome, you can enable "flags" to allow microphone detection on localhost (for example)
So, if you run the application locally, you will have to use a secured host or update you browsers settings to allow you to use the microphone.

Here is an example of my settings for chrome :
- url: chrome://flags/
- (#allow-insecure-localhost) "Allow invalid certificates for resources loaded from localhost" > enabled
- (#unsafely-treat-insecure-origin-as-secure) Insecure origins treated as secure > enabled (and i added my custom localhost urls : "http://dev.linto.local:8080,http://dev.linto.local:9001")
 
I hope this answer will help you, do not hestiate to get back to us for any question.

**Comment by PhMakowski** [comment]
thanks, so I have to put a proxy to do https or can we set the web app to use https ?

**Comment by rlopezdev** [comment]
Hi @PhMakowski,
For development, you can generate certificates for your localhost. I personnaly used "mkcert", but they are many ways to do it.
And for production, you will have to use a proxy.
